// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"database/sql"
	"time"
)

type Permission struct {
	ID            string       `json:"id"`
	Name          string       `json:"name"`
	Description   string       `json:"description"`
	ResourceName  string       `json:"resource_name"`
	AllowedRead   sql.NullBool `json:"allowed_read"`
	AllowedCreate sql.NullBool `json:"allowed_create"`
	AllowedUpdate sql.NullBool `json:"allowed_update"`
	AllowedDelete sql.NullBool `json:"allowed_delete"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
}

type Profile struct {
	UserID         string      `json:"user_id"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	Dob            time.Time   `json:"dob"`
	AddressLine1   string      `json:"address_line1"`
	AddressLine2   string      `json:"address_line2"`
	City           string      `json:"city"`
	State          string      `json:"state"`
	Country        string      `json:"country"`
	PostalCode     string      `json:"postal_code"`
	PrimaryPhone   string      `json:"primary_phone"`
	SecondaryPhone string      `json:"secondary_phone"`
	PrimaryEmail   string      `json:"primary_email"`
	SecondaryEmail string      `json:"secondary_email"`
	CreatedAt      interface{} `json:"created_at"`
	UpdatedAt      interface{} `json:"updated_at"`
}

type Role struct {
	ID           string       `json:"id"`
	Name         string       `json:"name"`
	Description  string       `json:"description"`
	IsActive     sql.NullBool `json:"is_active"`
	PermissionID string       `json:"permission_id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

type User struct {
	ID        string      `json:"id"`
	LoginID   string      `json:"login_id"`
	Password  string      `json:"password"`
	Status    string      `json:"status"`
	CreatedAt interface{} `json:"created_at"`
	UpdatedAt interface{} `json:"updated_at"`
}

type UserRole struct {
	UserID    string      `json:"user_id"`
	RoleID    string      `json:"role_id"`
	CreatedAt interface{} `json:"created_at"`
	UpdatedAt interface{} `json:"updated_at"`
}
